logging:
  level:
    root: ${LOG_LEVEL}
spring:
  application:
    name: clientappbackend
  main:
    web-application-type: servlet
  datasource:
    url: ${DB_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  web:
    cors:
      allowed-origins:
        - "http://localhost:8091"
        - "http://localhost:5174"
      allowed-methods:
        - GET
        - POST
      allowed-headers:
        - "*"
      allow-credentials: true
  security:
    oauth2:
      client:
        registration:
          eurodat:
            client-id: ${CLIENT_ID}
            client-authentication-method: private_key_jwt
            authorization-grant-type: client_credentials
            scope: openid
            provider: eurodat
        provider:
          eurodat:
            issuer-uri: https://app.int.eurodat.org/auth/realms/eurodat-int # most important if you provide issuer-uri then all the configuration will be automatically handled
      resourceserver:
        jwt:
          issuer-uri: http://localhost:20011/realms/data-provider
          jwk-set-uri: http://clientapp-keycloak:8080/realms/data-provider/protocol/openid-connect/certs

jks:
  base-path: https://app.int.eurodat.org/
  file-path: src/main/resources/keystore.jks
  certificate-alias: certificate
  password: ${JKS_PWD}
keycloak:
  client: clientapp-frontend

server:
  port: 8081
  servlet:
    context-path: /api
