logging:
    level:
        root: DEBUG
spring:
    application:
        name: datenmodellbackend
    main:
        web-application-type: servlet
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    security:
        oauth2:
            client:
                registration:
                    eurodat:
                        client-id: <tbd>
                        client-authentication-method: private_key_jwt
                        authorization-grant-type: client_credentials
                        scope: openid
                        provider: eurodat
                provider:
                    eurodat:
                        issuer-uri: https://app.int.eurodat.org/auth/realms/eurodat # most important if you provide issuer-uri then all the configuration will be automatically handled
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:20010/realms/dateninstitut
                    jwk-set-uri: http://localhost:20010/realms/dateninstitut/protocol/openid-connect/certs
jks:
    base-path: https://app.int.eurodat.org/
    file-path: datenmodell-backend/src/main/resources/keystore.jks
    certificate-alias: certificate
    password: <tbd>
keycloak:
    realm: datenmodell-frontend
server:
    servlet:
        context-path: /api
image-repository:
    user-id: <tbd>
    password: <tbd>
