openapi: 3.0.1
info:
  title: Datenmodell Backend API documentation
  version: 1.0.0
servers:
  - url: /api
paths:
  /study:
    get:
      tags:
        - study-controller
      summary: Retrieve study information.
      description: Information on all studies is retrieved.
      operationId: getAll
      responses:
        '200':
          description: Successfully retrieved study information.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StudyInformation'
        '401':
          description: Unauthorized
          headers:
            WWW-Authenticate:
              schema:
                type: string
        default:
          description: An error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - default-oauth: []
        - default-bearer-auth: []
  /transaction/{datasetId}/{dataAnalysisId}:
    post:
      tags:
        - transaction-controller
      operationId: postTransaction
      parameters:
        - name: datasetId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: dataAnalysisId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successfully completed a transaction.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResult'
        '401':
          description: Unauthorized
          headers:
            WWW-Authenticate:
              schema:
                type: string
        default:
          description: An error occurred
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
      security:
        - default-oauth: []
        - default-bearer-auth: []

components:
  schemas:
    StudyInformation:
      required:
        - id
        - title
        - content
        - identifiers
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
    TransactionResult:
      required:
        - datasetId
        - csvStr
      type: object
      properties:
        datasetId:
          type: string
          format: uuid
        csvStr:
          type: string
    ErrorDetails:
      required:
        - errorType
        - httpStatus
        - message
        - summary
      type: object
      properties:
        errorType:
          type: string
        summary:
          type: string
        message:
          type: string
        httpStatus:
          type: number
        metaInformation:
          type: object
    ErrorResponse:
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetails'
  securitySchemes:
    default-bearer-auth:
      type: http
      in: header
      scheme: bearer
    default-oauth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /keycloak/realms/dateninstitut/protocol/openid-connect/auth
          tokenUrl: /keycloak/realms/dateninstitut/protocol/openid-connect/token
          scopes: {}
