---
openapi: 3.1.0
components:
  schemas:
    WorkflowRegistrationRequest:
      type: object
      required:
      - workflowId
      - imageId
      - startCommand
      properties:
        imageId:
          type: string
        startCommand:
          type: array
          items:
            type: string
        workflowId:
          type: string
    TableSecurityMapping:
      type: object
      required:
      - rowBaseOutputSecurityColumn
      - tableName
      properties:
        rowBaseOutputSecurityColumn:
          type: string
        tableName:
          type: string
    ZonedDateTime:
      type: string
      format: date-time
      examples:
      - 2022-03-10T12:15:50-04:00
    AppResponse:
      type: object
      required:
      - id
      - transactionDDL
      - safeDepositDDL
      - tableSecurityMapping
      - workflows
      properties:
        transactionDDL:
          type: string
        safeDepositDDL:
          type: string
        id:
          type: string
        workflows:
          type: array
          items:
            $ref: "#/components/schemas/WorkflowDefinition"
        tableSecurityMapping:
          type: array
          items:
            $ref: "#/components/schemas/TableSecurityMapping"
    ImageRequest:
      type: object
      required:
      - location
      properties:
        registryUserName:
          type:
          - string
        registryPassword:
          type:
          - string
        location:
          type: string
    WorkflowDefinition:
      type: object
      required:
      - id
      - resourceName
      - entryPoint
      - startCommand
      - imageId
      properties:
        imageId:
          type: string
        resourceName:
          type: string
        id:
          type: string
        entryPoint:
          type: string
        startCommand:
          type: array
          items:
            type: string
    AppRegistration:
      type: object
      required:
      - id
      - transactionDDL
      - safeDepositDDL
      - tableSecurityMapping
      properties:
        transactionDDL:
          type: string
        safeDepositDDL:
          type: string
        id:
          type: string
        tableSecurityMapping:
          type: array
          items:
            $ref: "#/components/schemas/TableSecurityMapping"
    Image:
      type: object
      required:
      - id
      - sourceLocation
      - status
      - createdAt
      properties:
        createdAt:
          $ref: "#/components/schemas/ZonedDateTime"
        sourceLocation:
          type: string
        location:
          type:
          - string
        id:
          type: string
        status:
          type: string
    Unit:
      type: object
  securitySchemes:
    SecurityScheme:
      description: Authentication
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/v1/app-service/apps:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AppRegistration"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppResponse"
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppResponse"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Start App Registration
      tags:
      - App Resource
      security:
      - SecurityScheme: []
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Get All App Ids
      tags:
      - App Resource
      security:
      - SecurityScheme: []
  /api/v1/app-service/apps/{appId}:
    get:
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppResponse"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Find App
      tags:
      - App Resource
      security:
      - SecurityScheme: []
    delete:
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unit"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Delete App
      tags:
      - App Resource
      security:
      - SecurityScheme: []
  /api/v1/app-service/apps/{appId}/images:
    get:
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Image"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Get Images
      tags:
      - Image Resource
      security:
      - SecurityScheme: []
    post:
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ImageRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Create Image
      tags:
      - Image Resource
      security:
      - SecurityScheme: []
  /api/v1/app-service/apps/{appId}/images/{imageId}:
    get:
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      - name: imageId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Get Image
      tags:
      - Image Resource
      security:
      - SecurityScheme: []
    delete:
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      - name: imageId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Delete Image
      tags:
      - Image Resource
      security:
      - SecurityScheme: []
  /api/v1/app-service/apps/{appId}/workflows:
    get:
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Get Workflows
      tags:
      - Workflow Registration Resource
      security:
      - SecurityScheme: []
    post:
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WorkflowRegistrationRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unit"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Add Workflow
      tags:
      - Workflow Registration Resource
      security:
      - SecurityScheme: []
  /api/v1/app-service/apps/{appId}/workflows/{workflowId}:
    get:
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      - name: workflowId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkflowDefinition"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Get Workflow
      tags:
      - Workflow Registration Resource
      security:
      - SecurityScheme: []
    delete:
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      - name: workflowId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unit"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Delete Workflow
      tags:
      - Workflow Registration Resource
      security:
      - SecurityScheme: []
info:
  title: App Service REST API
  version: 1.0.0-SNAPSHOT
  description: OpenAPI specification of EuroDaT's App Service API
  contact:
    name: EuroDaT support
    url: https://www.eurodat.org
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://app.int.eurodat.org
- url: https://app.int.eurodat.org:8443
