---
openapi: 3.0.3
components:
  schemas:
    AppRegistration:
      type: object
      required:
      - id
      - transactionDDL
      - safeDepositDDL
      - tableSecurityMappings
      properties:
        id:
          type: string
        transactionDDL:
          type: string
        safeDepositDDL:
          type: string
        tableSecurityMappings:
          type: array
          items:
            $ref: "#/components/schemas/TableSecurityMapping"
        transactionTimeoutInDays:
          type: integer
          format: int32
    AppResponse:
      type: object
      required:
      - id
      - owner
      - transactionDDL
      - safeDepositDDL
      - tableSecurityMappings
      - workflows
      properties:
        id:
          type: string
        owner:
          type: string
        transactionDDL:
          type: string
        safeDepositDDL:
          type: string
        tableSecurityMappings:
          type: array
          items:
            $ref: "#/components/schemas/TableSecurityMapping"
        workflows:
          type: array
          items:
            $ref: "#/components/schemas/WorkflowDefinition"
        transactionTimeoutInDays:
          type: integer
          format: int32
    Image:
      type: object
      required:
      - id
      - sourceLocation
      - status
      - createdAt
      properties:
        id:
          type: string
        sourceLocation:
          type: string
        location:
          type: string
        status:
          $ref: "#/components/schemas/ImageStatus"
        createdAt:
          $ref: "#/components/schemas/ZonedDateTime"
    ImageRequest:
      type: object
      required:
      - location
      properties:
        location:
          type: string
        registryUserName:
          type: string
        registryPassword:
          type: string
    ImageStatus:
      type: string
      enum:
      - UPLOADING
      - ACTIVE
      - DELETING
      - INACTIVE
    TableSecurityMapping:
      type: object
      required:
      - rowLevelSecurityColumnName
      - tableName
      properties:
        rowLevelSecurityColumnName:
          type: string
        tableName:
          type: string
    WorkflowDefinition:
      type: object
      required:
      - id
      - resourceName
      - entryPoint
      - startCommand
      - imageId
      properties:
        id:
          type: string
        resourceName:
          type: string
        entryPoint:
          type: string
        startCommand:
          type: array
          items:
            type: string
        imageId:
          type: string
    WorkflowRegistrationRequest:
      type: object
      required:
      - workflowId
      - imageId
      - startCommand
      properties:
        workflowId:
          type: string
        imageId:
          type: string
        startCommand:
          type: array
          items:
            type: string
    ZonedDateTime:
      type: string
      format: date-time
      example: 2022-03-10T12:15:50-04:00
  securitySchemes:
    SecurityScheme:
      description: Authentication
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/v1/apps:
    post:
      operationId: startAppRegistration
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AppRegistration"
        required: true
      responses:
        "201":
          description: App registered successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppResponse"
        "401":
          description: Not authenticated
        "409":
          description: App already exists
        "403":
          description: Not Allowed
        "400":
          description: Bad Request
      summary: Start App Registration
      tags:
      - App Resource
      security:
      - SecurityScheme: []
    get:
      operationId: getAllAppIds
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Get All App Ids
      tags:
      - App Resource
      security:
      - SecurityScheme: []
  /api/v1/apps/{appId}:
    get:
      operationId: findApp
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppResponse"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Find App
      tags:
      - App Resource
      security:
      - SecurityScheme: []
    delete:
      operationId: deleteApp
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      responses:
        "204":
          description: App deleted successfully
        "401":
          description: Not authenticated
        "404":
          description: App with the specified ID not found
        "403":
          description: Not Allowed
      summary: Delete App
      tags:
      - App Resource
      security:
      - SecurityScheme: []
  /api/v1/apps/{appId}/images:
    get:
      operationId: getImages
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Images found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Image"
        "401":
          description: Not authenticated
        "404":
          description: App not found
        "403":
          description: Not Allowed
      summary: Get Images
      tags:
      - Image Resource
      security:
      - SecurityScheme: []
    post:
      operationId: createImage
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ImageRequest"
        required: true
      responses:
        "201":
          description: Image created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
        "401":
          description: Not authenticated
        "404":
          description: App not found
        "403":
          description: Not Allowed
        "400":
          description: Bad Request
      summary: Create Image
      tags:
      - Image Resource
      security:
      - SecurityScheme: []
  /api/v1/apps/{appId}/images/{imageId}:
    get:
      operationId: getImage
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      - name: imageId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Image found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
        "401":
          description: Not authenticated
        "404":
          description: App or image not found
        "403":
          description: Not Allowed
      summary: Get Image
      tags:
      - Image Resource
      security:
      - SecurityScheme: []
    delete:
      operationId: deleteImage
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      - name: imageId
        in: path
        required: true
        schema:
          type: string
      responses:
        "202":
          description: Image deletion started
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
        "400":
          description: Image cannot be deleted
        "401":
          description: Not authenticated
        "404":
          description: App or image not found
        "403":
          description: Not Allowed
      summary: Delete Image
      tags:
      - Image Resource
      security:
      - SecurityScheme: []
  /api/v1/apps/{appId}/workflows:
    get:
      operationId: getWorkflows
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Workflows found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "401":
          description: Not authenticated
        "404":
          description: App not found
        "403":
          description: Not Allowed
      summary: Get Workflows
      tags:
      - Workflow Registration Resource
      security:
      - SecurityScheme: []
    post:
      operationId: addWorkflow
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WorkflowRegistrationRequest"
        required: true
      responses:
        "201":
          description: Workflow created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkflowDefinition"
        "401":
          description: Not authenticated
        "400":
          description: Bad request
        "409":
          description: Workflow with the same name already exists for the app
        "403":
          description: Not Allowed
      summary: Add Workflow
      tags:
      - Workflow Registration Resource
      security:
      - SecurityScheme: []
  /api/v1/apps/{appId}/workflows/{workflowId}:
    get:
      operationId: getWorkflow
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      - name: workflowId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Workflow found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkflowDefinition"
        "401":
          description: Not authenticated
        "404":
          description: Workflow or app not found
        "403":
          description: Not Allowed
      summary: Get Workflow
      tags:
      - Workflow Registration Resource
      security:
      - SecurityScheme: []
    delete:
      operationId: deleteWorkflow
      parameters:
      - name: appId
        in: path
        required: true
        schema:
          type: string
      - name: workflowId
        in: path
        required: true
        schema:
          type: string
      responses:
        "204":
          description: Workflow deleted
        "401":
          description: Not authenticated
        "404":
          description: Workflow or app not found
        "403":
          description: Not Allowed
      summary: Delete Workflow
      tags:
      - Workflow Registration Resource
      security:
      - SecurityScheme: []
info:
  title: App Service REST API
  version: 1.0.0-SNAPSHOT
  description: OpenAPI specification of EuroDaT's App Service API
  contact:
    name: EuroDaT support
    url: https://www.eurodat.org
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://app.int.eurodat.org
- url: https://app.int.eurodat.org:8443
